### ISSUE TITLE
Accounts created via test faucet not being available in the test network

### ISSUE THREAD

**Issue by gazoscalvertos** [ripple/testnet-faucet#1]
Hi,

Accounts created and pre-funded using the [test faucet](https://developers.ripple.com/xrp-test-net-faucet.html) are not being recognised (RippledError: Account not found) in the testnet

[cross post issue](https://github.com/ripple/ripple-dev-portal/issues/520)

I have tried both using javascript (ripple-lib) using server 'wss://s.altnet.rippletest.net:51233' and via the [developer portal](https://developers.ripple.com/send-xrp.html).

**Comment by mDuo13** [comment]
Was able to reproduce it myself. It appears to be an outage somewhere.

**Comment by gazoscalvertos** [comment]
Is there an XRP finders fee 🤣😂🤣

It would be great to get this sorted, thanks for the rapid response

**Comment by leebow** [comment]
Can confirm I'm experiencing the same issue. Any idea how we can escalate this?

**Comment by ximinez** [comment]
It's working again, thanks to @intelliot's hard work, and should be more stable going forward.
